### ISSUE TITLE
DPI to low on Akatsuki

### ISSUE THREAD

**Issue by Thaodan** [sailfishos-sony-tama/main#83]
On the Xperia XZ3 the DPI is too low resulting in to small launcher icons and to small fonts in some apps.

**Comment by rinigus** [comment]
related to https://github.com/sailfishos-sony-tama/main/issues/60

**Comment by Thaodan** [comment]
Ah didn't saw that. Ab workaround is to use https://coderus.openrepos.net/pm2/project/launcher-combined and  zoom the icons.

**Comment by rinigus** [comment]
It is not really port's fault, but general availability of icons for hidpi. If you could write up summary, let's add it to README under tips.

**Comment by rinigus** [comment]
TJC: https://together.jolla.com/question/220290/pixel_ratio-limitation-for-high-resolution-screens/

**Comment by rinigus** [comment]
Should be fixed upstream by Jolla.

**Comment by Thaodan** [comment]
Yet it still exists. It doesn't make 
sense to close it since its an 
existing bug.

**Comment by rinigus** [comment]
It does make sense to close it as it is not something we, as porters, can fix. As such, it is not then the bug of a port, but is a bug for upstream (SFOS in this case). Corresponding message has been sent to TJC as well as SFO, so we have reported it where it belongs.

Closing it here to avoid being distracted by something which is out of our hands anyway.

**Comment by Thaodan** [comment]
There are bigger icon resolutions now:
https://github.com/mer-hybris/droid-hal-configs/pull/255

The icons do exist since 4.5.x

**Comment by rinigus** [comment]
Thanks!
